### ISSUE TITLE
Unclosed client sessions

### ISSUE THREAD

**Issue by HanYangZhao** [titilambert/pyhydroquebec#10]
Hi,

I get this error when i run the the -j flag. The data prints fine, but  the session is not closed?

`Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E116C6CDA0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000001E11774E908>, 343340.5                                                                                                                                   93)]']
connector: <aiohttp.connector.TCPConnector object at 0x000001E116C6CE10>
Unclosed connection
client_connection: Connection<ConnectionKey(host='www.hydroquebec.com', port=443, ssl=True)`

Any idea what caused it?

**Comment by titilambert** [comment]
Hello, I can not reproduce this issue :/
Could you provide me the entire command line (without password/user ;) ) and the full output ?
Thanks !

**Comment by titilambert** [comment]
I think I found it !
It will be fixed in version 2.2.1
