### ISSUE TITLE
TypeError exception in 2.1.0

### ISSUE THREAD

**Issue by souellet-mn** [titilambert/pyhydroquebec#11]
Hi,

I am kinda new to the whole home-assistant and was very pleased to see a sensor for hydro-quebec. I am trying to use it within home-assistant 0.66.5, but I have the following error. I've tried to use the pyhydroquebec program directly and have the same issue. When I call the program with only my username and password, I can see my data but the same error occurs once my contract information is print to the console.

/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py:358: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self._session.close()
Task exception was never retrieved
future: <Task finished coro=<HydroQuebecClient.fetch_data() done, defined at /srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py:286> exception=TypeError('Invalid variable type: mapping value should be str or int, got None',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 323, in fetch_data
    daily_data = yield from self._get_daily_data(p_p_id, start_date, end_date)
  File "/srv/homeassistant/lib/python3.5/site-packages/pyhydroquebec/client.py", line 273, in _get_daily_data
    timeout=self._timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client.py", line 312, in _request
    ssl=ssl, proxy_headers=proxy_headers)
  File "/srv/homeassistant/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 181, in __init__
    url2 = url.with_query(params)
  File "/srv/homeassistant/lib/python3.5/site-packages/yarl/__init__.py", line 851, in with_query
    new_query = self._get_str_query(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/yarl/__init__.py", line 819, in _get_str_query
    "should be str or int, got {!r}".format(v))
TypeError: Invalid variable type: mapping value should be str or int, got None
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x75f36830>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x754c0ef0>, 181330.768492032)]']
connector: <aiohttp.connector.TCPConnector object at 0x75f36810>
Unclosed connection
client_connection: Connection<ConnectionKey(host='www.hydroquebec.com', port=443, ssl=True)>

Any ideas?

**Comment by titilambert** [comment]
Hello, I just push an update for th hydroquebec component on Home assistant: https://github.com/home-assistant/home-assistant/pull/13586
If you know how to test it without waiting the next version it could be nice !
By the sometimes the hydroquebec website is not reachable, so you could reach some issue like this one...

**Comment by souellet-mn** [comment]
Thanks, I will try it as soon as I get home.

**Comment by souellet-mn** [comment]
Firstly, I still have the issue using v2.2.1.

Secondly, I've done a bunch of debugging onto pyhydroquebec master branch and I think I found why I got that error. In my account I have 2 contracts, one old which is canceled. The other, the one I want to retrieve information from, is new. The first period is not completed yet. Prior to calling the _get_daily_data, the end_date variable is None. I assume this is because it is the first ever period of this contract. Retrieve information from the old contract works fine.

Any workaround for the first period or do I have to wait for the next period?

**Comment by titilambert** [comment]
@souellet-mn Sorry for the delay. Unfortunately not :/ It's really hard to handle that can of change without accessing to the account :/
I'm closing this issue in favor of this one #25

**Comment by titilambert** [comment]
For all users of this component, please read: https://github.com/titilambert/pyhydroquebec/issues/26

**Comment by titilambert** [comment]
I'm closing this issue because of the Hydroquebec update see https://github.com/titilambert/pyhydroquebec/issues/35
