### ISSUE TITLE
KeyError: 'yesterday_hourly_consumption'

### ISSUE THREAD

**Issue by b0ne** [titilambert/pyhydroquebec#27]
**Describe the bug**
Error when running the -H option
<img width="425" alt="2018-12-01 15_22_52-select pi raspcatfeeder_" src="https://user-images.githubusercontent.com/971968/49341793-76f5b280-f620-11e8-9c6d-6e33ba1f0e43.png">

When running the -j:
{"contractNumber": {"period_total_bill": _Number_, "annual_date_end": "", "period_average_temperature": -2, "annual_date_start": "", "period_mean_daily_bill": _Number_, "annual_total_consumption": "", "balance": 0.0, "period_projection": _Number_, "yesterday_lower_price_consumption": _Number_, "annual_mean_daily_consumption": "", "yesterday_higher_price_consumption": 0, "annual_kwh_price_cent": "", "period_total_days": 61, "annual_length": "", "period_lower_price_consumption": _Number_, "period_mean_daily_consumption": _Number_, "period_higher_price_consumption": 0, "yesterday_total_consumption": _Number_, "period_length": 42, "period_total_consumption": _Number_, "yesterday_average_temperature": -3, "annual_mean_daily_bill": "", "annual_total_bill": ""}}

yesterday_hourly_consumption is not there

Running witouth -H dons't feedback error

**Comment by titilambert** [comment]
I'm closing this issue because of the Hydroquebec update see https://github.com/titilambert/pyhydroquebec/issues/35
