### ISSUE TITLE
Add option to disable get_hourly_data

### ISSUE THREAD

**Issue by jingl3s** [titilambert/pyhydroquebec#28]
Hello,

I get some issues when I use daily calls to pyhydroquebec. Most of them, when I can catch the error, are related to the hourly.

Could you add an argument to disable that feature when retrieving information ?

Thanks a lot.

**Comment by b0ne** [comment]
The error maybe link to : https://github.com/titilambert/pyhydroquebec/issues/29

**Comment by jingl3s** [comment]
Year same as #29 but my request is to disable this request I did not use it in my daily retrieve value

**Comment by jingl3s** [comment]
As another issue is raised this one could be closed
