### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by b0ne** [titilambert/pyhydroquebec#29]
**Describe the bug**
Error when trying to get the data from HydroQuebec

**To Reproduce**
The command pyhydroquebec -u username -p password  (-j and witouth -j) return an error

> Task exception was never retrieved
future: <Task finished coro=<HydroQuebecClient.fetch_data() done, defined at /usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py:388> exception=IndexError('list index out of range',)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py", line 415, in fetch_data
    hourly_data = yield from self._get_hourly_data(day_date, p_p_id)
  File "/usr/local/lib/python3.5/dist-packages/pyhydroquebec/client.py", line 334, in _get_hourly_data
    hourly_weather_data = json_output['results'][0]['listeTemperaturesHeure']
IndexError: list index out of range 

Seem linked to the fact that HydroQuebec dosn't register all the data yesterday

![image](https://user-images.githubusercontent.com/971968/49389457-572fbe80-f6f4-11e8-9d6c-0672b4b679e7.png)

**Comment by b0ne** [comment]
@titilambert 

Hi, I looked the code at the line 334 and it seem to try to get the value at position 0 of the array Json_Ouput['result'] and then get an error because the array seem to be empty. I modified the code to add a verification that the length of the arrary is >1 and if not then to do the same thing if the temperature data was missing.

> if

 not json_output.get('results'):
            # Missing Temperature data from Hydro-Quebec (but don't crash the app for that)
            hourly_weather_data = [None]*24
        elif len(json_ouput['results'])<1:
            # Data from Hydro-Quebec isn't good (but don't crash the app for that)
            hourly_weather_data = [None]*24
        else:
            hourly_weather_data = json_output['results'][0]['listeTemperaturesHeure'] <

It seem to work for me!

**Comment by titilambert** [comment]
I really don't understand you patch, It should handle by 
```
if not json_output.get('results'):
```
This is really strange...


Could you add : 
```
print(json_output):
```
To see the value of the variable ?

Thanks !

**Comment by b0ne** [comment]
The 
`if not json_output.get('results')`
work if its returning None, but if it returning an empty array it will pass

**Comment by b0ne** [comment]
Here the print value : {'success': True, 'results': []}

**Comment by titilambert** [comment]
I'm really not sure of that.
Could you try this command line ?
```
python3 -c "print('EMPTY') if not [] else print('NOT EMPTY')"
```

**Comment by b0ne** [comment]
python3 -c "print('EMPTY') if not [] else print('NOT EMPTY')"

EMPTY

**Comment by b0ne** [comment]
Here the print value : {'success': True, 'results': []}

So in this case i think the 
`if` not json_output.get('results') 

Get the result from sucess : true! and not the result []

**Comment by titilambert** [comment]
I'm closing this issue because of the Hydroquebec update see https://github.com/titilambert/pyhydroquebec/issues/35
