### ISSUE TITLE
Web page changes announced for september 30 2019

### ISSUE THREAD

**Issue by kevmegforest** [titilambert/pyhydroquebec#35]
I just received an email where they announced they will change the login setup and surely the web page contents too by September 30. (the image provided is surely not the current UI)

I don't know how this project can prepare itself for the changes.

Here is the content of the email:

Notice to business customers | September 9, 2019

Consolidating your accounts

Hello,We are pleased to announce that, as of September 30, 2019, you will be able to access all your accounts (residential, business and those for which you are a proxy holder) from the same Customer Space.We’re also making it easier to log into your Customer Space: instead of having to manage many different access codes, you’ll be able to log in with your email address.According to our files, the email address hydroquebec_monitor@xxxx.ca is linked to several Customer Space accounts. 

![image](https://user-images.githubusercontent.com/1432145/64559920-655edb00-d315-11e9-9d22-554223797462.png)

To consolidate your accounts, contact your agent at 1 800 463-9900, from 8:30 a.m. to 4:30 p.m., Monday to Friday. 

If you would prefer to consolidate your accounts yourself, you may do so as of September 30, 2019. Simply log into each account and enter the same email address.

Thank you for your cooperation.

Yours truly,

**Comment by titilambert** [comment]
Thanks for the update, I didn't get this warning.
Today, October 4, everything works for me. Could you confirm that is good to you ?

**Comment by kevmegforest** [comment]
I received another email from HQ that said they would report it 1 week later until october 7th.

It sure for me will be a lot easier to manage all those proxy accounts, I hope. With 100 clients that's a lot of duplicated user names and passwords

**Comment by titilambert** [comment]
Ok, Thanks ! Are those accounts business accounts ?
I'm closing this issue, but please reopen it if you have any new issue next week

**Comment by gleepwurp** [comment]
Stopped working for me today!  I got this error message: 

`2019-10-06 20:49:37 ERROR (MainThread) [homeassistant.components.hydroquebec.sensor] Error on receive last Hydroquebec data: No login form find
`

**Comment by kevmegforest** [comment]
> Ok, Thanks ! Are those accounts business accounts ?
> I'm closing this issue, but please reopen it if you have any new issue next week

Yes, they are business accounts. 

It seems that their web site is still down for maintenance. The upgrade of their website may be more complicated then they thought

**Comment by sebauclair** [comment]
Site is back online but know I have SSL certifcate error..do you know how to correct it?  Thanks

**Comment by gleepwurp** [comment]
hmm, when I try to navigate to the API logon screen, I get an error message from Hydro's website:

https://www.hydroquebec.com/portail/web/clientele/authentification (taken from the scritp)

"Désolé, une erreur est survenue."

So, they might have changed their login page/location...

G.

**Comment by gleepwurp** [comment]
Looks like access to "Espace Client" has changed to :

https://connexion.hydroquebec.com/hqam/XUI/?realm=/clients#login/

But I might be way off base here, I'm really not an expert in this...

G.

**Comment by titilambert** [comment]
This library is broken since 2019-10-08 after a huge Hydroquebec website change ...

**Comment by starwolf73** [comment]
Ouch... Well thanks @titilambert for all the work so far as this was great implementation to my HA. In hope we can fix it back... Guest I'll need to learn python and wet my hands with this project to help the community back.

**Comment by llluis** [comment]
Very sad with the breaking change... Also, HomeAssistant will drop this integration altogether: https://github.com/home-assistant/home-assistant/issues/27373

I plan to keep it as custom integration.

**Comment by starwolf73** [comment]
> Very sad with the breaking change... Also, HomeAssistant will drop this integration altogether: [home-assistant/home-assistant#27373](https://github.com/home-assistant/home-assistant/issues/27373)
> 
> I plan to keep it as custom integration.

@llluis Same here, just sad as this was a great integration. Will have to run in custom integration once we can fix the authentication method as the site doesn't seem to be change (unless I missed something). Will have been great if HQ was providing API to expose those information. Did a quick search but so far didn't find anything.

**Comment by lucboudreau** [comment]
I did a quick investigation to see what changed. Put the details here. Let us know when this integration moves into a custom project. I'd also like to have it and help maintain if I can.

https://github.com/home-assistant/home-assistant/issues/27373

**Comment by titilambert** [comment]
Hello !
Finally I got some good news ! I'm able to login and fetch all the previous data !
I'm currently completing the CLI. Then I will complete the mqtt for home assistant

**Comment by titilambert** [comment]
Here the new branch 3.x: https://github.com/titilambert/pyhydroquebec/tree/3.x
HELP IS NEEDED !!
I need help to complete the `outputter.py` file to complete text, influx and json outputs.
The detailed view is not completed neither, help is also needed there.
I put the tag `#FIXME where help is needed.
If you want to help, please submit your PR to the 3.x branch (not master)

Thanks a lot !

I will continue to work on the MQTT Daemon, and do some clean up.

By the way, I'm thinking migrating the project to Gitlab.com, to use the integrated CI system...

**Comment by gleepwurp** [comment]
Hi!

Do you have any details as to the inputs definitions and output requirements, outside of JSON/InfluxDB?

IE, what is the "contract" format?  A list of contracts?  a structure containing everything?  a single contract number? Should the output follow a specific structure hierarchy?

Thanks,

G.

**Comment by titilambert** [comment]
> Very sad with the breaking change... Also, HomeAssistant will drop this integration altogether: [home-assistant/home-assistant#27373](https://github.com/home-assistant/home-assistant/issues/27373)
> 
> I plan to keep it as custom integration.
@llluis The Hydroquebec new website is really slow... I'm sure it's a good idea to keep it as an integration, it will slow down the Home-Assistant startup...

**Comment by ncareau** [comment]
@titilambert Great news ! That was fast. 

I'll take a look tonight to see if i can complete a few things.

**Comment by titilambert** [comment]
@gleepwurp I just added an option `-D` to dump the contract object as a dict. I hope it's help

**Comment by titilambert** [comment]
The MQTT daemon is working ! Next step Dockerfile and Kubernetes manifests !

**Comment by lucboudreau** [comment]
I sent you a quick PR so I can set the MQTT root topic from the config.yaml file.

https://github.com/titilambert/pyhydroquebec/pull/39/files

Also I looked into making the daemon less daemon-y, but my Python skills and my knowledge of asyncio is limited. Basically, I'd like to be able to run the mqtt part from a cron job. I would rather have it configured through cron and not have it maintain a MQTT connection for nothing. Any pointers?

**Comment by titilambert** [comment]
I just updated the Readme file with the link to the docker images ! ;)

**Comment by titilambert** [comment]
> I sent you a quick PR so I can set the MQTT root topic from the config.yaml file.
> 
> https://github.com/titilambert/pyhydroquebec/pull/39/files
> 
> Also I looked into making the daemon less daemon-y, but my Python skills and my knowledge of asyncio is limited. Basically, I'd like to be able to run the mqtt part from a cron job. I would rather have it configured through cron and not have it maintain a MQTT connection for nothing. Any pointers?

Maybe the CLI could have a new option ?

 
> Oh and also you should add some docs regarding the version of Python required. Took me some messing around to figure out we need 3.7+.

**Comment by titilambert** [comment]
Add a new issue about MQTT output https://github.com/titilambert/pyhydroquebec/issues/42

**Comment by titilambert** [comment]
I'm closing this issue.
If you find any issue with the new version, please open a new issue ;)
I will release a new version on pypi shortly
