### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by QcVictor** [titilambert/pyhydroquebec#4]
Got this error with latest release `'NoneType' object has no attribute 'text'`

**Comment by titilambert** [comment]
Thanks for reporting

Could you give me the full error output ?

Thanks !

**Comment by titilambert** [comment]
@QcVictor I think I found the issue, could you test with the 2.0.2 version ?
Thanks !

**Comment by QcVictor** [comment]
same thinks:-(
`iMac-de-Pascal-2:~ Pascal$ pip install pyhydroquebec
Requirement already satisfied: pyhydroquebec in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pyhydroquebec)
Requirement already satisfied: bs4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from pyhydroquebec)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->pyhydroquebec)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->pyhydroquebec)
Requirement already satisfied: idna<2.6,>=2.5 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->pyhydroquebec)
Requirement already satisfied: urllib3<1.22,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from requests->pyhydroquebec)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from bs4->pyhydroquebec)
iMac-de-Pascal-2:~ Pascal$ pyhydroquebec -u xxxxx -p xxxxx
'NoneType' object has no attribute 'text'
iMac-de-Pascal-2:~ Pascal$`

**Comment by titilambert** [comment]
For sure you need  beautiful soup AND aiohttp
Can you try:
```
virtualenv -p /usr/bin/python3 env
source env/bin/activate
pip install -r requirements.txt
python setup.py develop
pyhydroquebec ....
```

If this is not working,
could you give me more details on your Hydroquebec account: 
* Contract Type: D, DT, ...
* Multi contracts: Yes/No
* Equal payments: Yes/No
* Contract age: Less than one year old 
* Other contract specificity

**Comment by QcVictor** [comment]
Ok I got it working in the virtual environment with my ubuntu, when I tried 
`pi@DomoticzTest:~$ pip install pyhydroquebec
Collecting pyhydroquebec
  Using cached pyhydroquebec-2.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Sorry, Python < 3.4 is not supported
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6YLu0r/pyhydroquebec/
pi@DomoticzTest:~$ 
`

    Contract Type: D
    Multi contracts: No
    Equal payments: No
    Contract age: more than one year old
    Other contract specificity none

**Comment by titilambert** [comment]
@QcVictor thanks !
Your contract is like mine, so it should work...
Which python version  are you using ?
Please try (inside AND ousite the virtualenv) : ```python -V```
You MUST use python > 3.4

Also, I saw that you are using it with Domoticz. I guess you have to tell to Domoticz to use python 3. (I don't know how to do that)
BTW, I'm using Home Assistant where this library is working really well.

**Comment by QcVictor** [comment]
Both version of python are installed, 2.7.12 and 3.5.1-3, should be the trick not sure why he fail...

**Comment by titilambert** [comment]
coudl you try ```python -V``` ? just before you launch the pyhydroquebec command

**Comment by QcVictor** [comment]
python -V give me Python 2.7.12

**Comment by QcVictor** [comment]
Now I have to find a way for push it in domoticz

**Comment by titilambert** [comment]
@QcVictor yes ! How domoticz is handling python3 component ?

**Comment by QcVictor** [comment]
looks like in beta https://www.domoticz.com/wiki/Using_Python_plugins

**Comment by titilambert** [comment]
Also, be carefull, the last version of PyHydroQuebec is based on asyncio and aiohttp. So you have to be sure that Domoticz is handling that

**Comment by titilambert** [comment]
I'm closing this issue, but you can still write comments/question in it if needed
