### ISSUE TITLE
Hourly consommation

### ISSUE THREAD

**Issue by arnaud-42** [titilambert/pyhydroquebec#6]
Hi,

is there any way to get the new hourly data ?

**Comment by arnaud-42** [comment]
After some test i think we can get data for the current day.
HQ doesn't show the data but they are in ths json file

**Comment by titilambert** [comment]
OH ! Do you mean that we can get data detailed per hour ?!
I can not see it now, because I changed my contract with Hydroquebec and I don't have any data (on the Hydroquebec website) until end of january :/
So, for sure, when I'm able to gather hourly data, I will add it to this lib !
Thanks !

**Comment by titilambert** [comment]
@arnaud-42 by the way what is the url of the json file ?

**Comment by arnaud-42** [comment]
resource_id=resourceObtenirDonneesConsommationHoraires&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&date=2017-12-18

**Comment by titilambert** [comment]
Nice ! Thanks !
So, for sure, when my data came back, I'm adding this to this lib and to Home-Assistant !

**Comment by arnaud-42** [comment]
also you can grab the temp for each hour here : 
resourceObtenirDonneesMeteoHoraires&p_p_cacheability=cacheLevelPage&p_p_col_id=column-2&p_p_col_count=1&dateDebut=2017-12-18&dateFin=2017-12-18

I really like to have this value with the amount of energy I used ...

**Comment by titilambert** [comment]
Cool ! Thanks !

**Comment by titilambert** [comment]
@arnaud-42 I just push a new commit to handle this.
Could you confirm this is working for you ?
Thanks !

**Comment by arnaud-42** [comment]
Hello, sorry for the late answer i was away.
Your code almost work :)

I think there is a hardcoded date here : 
@asyncio.coroutine
    def _get_hourly_data(self, day_date, p_p_id):
        day_date="2018-02-17"
