### ISSUE TITLE
MQTT Integration  enhancement 

### ISSUE THREAD

**Issue by QcVictor** [titilambert/pyhydroquebec#9]
MQTT Integration will be great, easily integration in various home automation software no hassle :-)

**Comment by titilambert** [comment]
Hello, thanks for bringing this idea !
I guess to do that we have to turn pyhydroquebec as a daemon and send data throught MQTT.
I don't know if I have to do it, but I'm really open to contribution and enhancement !

**Comment by QcVictor** [comment]
Quick read on this subject look like somethings feasible, unfortunately I'm not very helpful. I have limited knowledge for coding..

**Comment by titilambert** [comment]
https://github.com/titilambert/pyhydroquebec/pull/38 fixes it
